const endpoints = {
  login: '/auth/token',
  logout: '/auth/logout',
  me: '/user-view',
  resetPasswordStaff: `/api/users/staff/password/update`,
  resetPasswordMerchant: `/api/users/merchant/password/update`,
  reportBilling: 'reports/billing-report',
  reportBnpl: 'reports/bnpl',
  reportBriefcase: 'reports/briefcase',
  reportByRegions: 'reports/report-regions',
  reportByMerchants: 'reports/report-merchant',
  reportByStatus: 'reports/report-status',
  reportByExitensionBnpl: 'reports/extension-bnpl',
  getBrokerKey: (id: number) => `api/merchants/broker/${id}`,
  getUserByID: (id: any) => `/auth/user/${id}`,
  merchant: `api/merchants`,
  categories: `dictionaries/categories`,
  applicationMerchant: '/api/merchants/application/user',
  district: `/dictionaries/districts`,
  region: `/dictionaries/regions`,
  banks: `dictionaries/banks`,
  bankBranch: `dictionaries/bankBranch`,
  usersStaff: `api/users/staff`,
  limitData: '/application/period-summ',
  reportsExpense: '/reports/expense',
  merchantUsersId: (id: any) => `/api/users/merchant/${id}`,
  merchantClientsFilter: `/api/merchants/filter/clients`,
  getStatisticMerchant: `api/merchants/get/stats`,
  branchesMerchant: `branches/merchant`,
  applicationInfoByID: (id: any) => `/application/informations/${id}`,
  applicationApprovedFilter: '/application/approved/filter',
  applicationApprovedMerchants: '/application/approved/filter/merchants',
  branches: 'branches',
  applicationByersByID: (id: any) => `/application/buyer/${id}`,
  productPost: '/products',
  productGetByID: (id: any) => `/products/${id}`,
  productDelete: (id: any) => `/products/product/${id}`,
  applicationRejectByID: (id: any) => `/application/${id}/reject`,
  merchantUsers: (id: any) => `/api/merchants/users/${id}`,
  brachUser: '/branches/branch/users',
  branch: '/branches/branch',
  applicationById: (id: number) => `/application/applications/${id}`,
  merchantApplication: '/application/user',
  userApplicationList: (id: any) => `application/user/${id}`,
  applicationAll: '/application/all',
  applicationClient: '/api/merchants/get/applications',
  period: '/handbook/tariff-period',
  schedule: (id: any) => `application/schedule/${id}`,
  rate: '/handbook/tariff-rate',
  periodRate: '/handbook/period-rate',
  applicationCreate: '/application/create',
  applicationVerify: '/application/verify',
  merchantClients: (id: any) => `/api/merchants/clients/${id}`,
  branchClients: (id: any) => `/branches/clients/${id}`,
  loginClient: '/auth/sign-in-client',
  resendOtp: (id: any) => `/otp/resend/${id}`,
  resendOtpApplication: (id: any) => `/application/resend/${id}`,
  applicationDecide: '/application/decide',
  applicationGetById: (id: any) => `/application/get/${id}`,
  bankBraches: `/dictionaries/bankBranch`,
  bankBrachById: (id: any) => `/dictionaries/bankBranch/${id}`,
  applicationApprovedByID: (id: any) => `/application/approve/${id}`,
  bincodes: '/dictionaries/bincodes',
  bincodeById: (id: any) => `/dictionaries/bincodes/${id}`,
  applicationOtp: '/application/otp',
  resendContract: (id: number) => `/application/resend-contract/${id}`
}

export default endpoints
